/*************************************************************************
* Omukade Auto Procedual Assembly Rewriter ("AutoPAR")
* (c) 2023 Hastwell/Electrosheep Networks 
* 
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as published
* by the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU Affero General Public License for more details.
* 
* You should have received a copy of the GNU Affero General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.
**************************************************************************/

using Mono.Cecil;
using System.Runtime.CompilerServices;

namespace Omukade.AutoPAR
{
    public static class CecilExtensions
    {
        /// <summary>
        /// Determines if the specified member is compiler-generated by checking for <see cref="CompilerGeneratedAttribute"/>.
        /// </summary>
        /// <param name="icap">The member that should be checked for <see cref="CompilerGeneratedAttribute"/>.</param>
        /// <returns>Whether the member has <see cref="CompilerGeneratedAttribute"/> defined on it.</returns>
        public static bool IsCompilerGenerated(this ICustomAttributeProvider icap)
        {
            foreach(var attrib in icap.CustomAttributes)
            {
                if(attrib.AttributeType.Name == nameof(CompilerGeneratedAttribute)) return true;
            }

            return false;
        }
    }
}
